"""Add conversion units

Revision ID: 323c08c493b0
Revises: 0c680c3dd42c
Create Date: 2025-12-08 05:22:06.127856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323c08c493b0'
down_revision = '0c680c3dd42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conversion_rate', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('conversion_rate')
        batch_op.drop_column('purchase_unit')

    # ### end Alembic commands ###
