"""Initial migration

Revision ID: a1a4ddd52296
Revises: 
Create Date: 2025-12-08 23:49:03.920540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a4ddd52296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conversion_rate', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('customer_name')
        batch_op.drop_column('status')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('conversion_rate')
        batch_op.drop_column('purchase_unit')

    # ### end Alembic commands ###
